version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - ./node_modules
      - .:/usr/app/frontend
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - ./node_modules
      - .:/usr/app/frontend
    command: ["npm","run","test"]